services:
  nginx:
    image: nginx:latest
    volumes:
      - ./docker/nginx/templates/:/etc/nginx/templates
      - "./:/app"
    ports:
      - "8000:80"

  app:
    image: app
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    volumes:
      - ./:/app
    user: ${UGID}
